apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewaycore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewaycore
      version: 'v1'
  template:
    metadata:
      labels:
        app: gatewaycore
        version: 'v1'
    spec:

      terminationGracePeriodSeconds: 10
      containers:
        - name: gatewaycore-app
          image: xxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/gateway:latest
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/config
            - name: JHIPSTER_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-secret
                  key: registry-admin-password
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://admin:${jhipster.registry.password}@jhipster-registry.default.svc.cluster.local:8761/eureka/
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://xxxxxxxxx-xxxxxxxx.xxxxxxxxxxxxxxx.us-west-1.rds.amazonaws.com:5432/dbname?usessl=false
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: Xxxxxxxxxxxxxxx_2019
          ports:
            - name: http
              containerPort: 8080

